### ISSUE TITLE
Problem importing the module

### ISSUE THREAD

**Issue by TwanoO67** [shreekantha/ng2-googlechart#2]
Hello,

I'm trying to import your module in a project.
But then I have an error " UnhandledPromiseRejectionWarning: Error: Ng2GoogleChartModule is not an NgModule "

Do you already have seen that ?

**Comment by shreekantha** [comment]
Hi @TwanoO67 , Sorry for the late response, I was not keeping well so I could not replay to your message.
Same thing we are also using with our internal project its working fine.
Below is the link for demo site, where I explained all the steps to follow.
[Demo site link](http://shreekantha.github.io/ng2-googlechart/)
